### ISSUE TITLE
Build, run Refined natively on Linux.

### ISSUE THREAD

**Issue by chopraaa** [Asunaya/RefinedGunz#18]
Is it planned somewhere along the road?

The benefits far outweigh using Windows to run servers, and encourage _a lot_ of third-party development.

**Comment by Asunaya** [comment]
Yeah, totally.

Linux benefits servers the most AFAIK, so porting MatchServer is the main priority right now. I've segregated most of the platform-specific code (MProcess.h, MFile.h, etc.), and I just need to write simple Linux implementation for them.

The non-trivial things that need to be ported, off the top of my head, are:

- MRealCPNet, which uses I/O completion ports to implement async I/O. This doesn't have any direct analogue in Linux, so some kind of abstraction has to take place.
- MXml, which needs to be implemented with RapidXML instead of MSXML.
- Support for another cross-platform DBMS (e.g. PostgreSQL or MySQL). Right now, MSSQL and SQLite are supported, but MSSQL is Windows-only, and while SQLite works fine on small servers, I'm not sure how well it will hold up with large datasets and multiple sources querying it.

I'd like to port Gunz too, but it seems like much more work, with much lower reward, given that most gamers don't use Linux. I might just get it to work on emulators without bugs mainly (I think it's pretty buggy right now?), and leave it at that for a while, while working on porting it in the long-term.

**Comment by chopraaa** [comment]
Thanks for the response. Once you get to it, I'd like to offer assistance with testing and possibly sponsor a server to bug test the source itself. That way we can get more issues reported without people setting up the server themselves.

+1 for MySQL/MariaDB. I don't see Postgre being a good fit for Gunz. It's better on a really large scale, a scale which Gunz doesn't need IMHO. 😆 

The game itself doesn't need to be ported and I don't really see it as a profitable long term goal. The focus should just be on making the game more playable than it's current form and making it fit for the 21st century.

**Comment by chopraaa** [comment]
MSSQL 2017 has support for Linux so I guess that's good news.

**Comment by Asunaya** [comment]
Hey, I've gotten MatchServer sorta working on Linux just now. It doesn't support anything other than SQLite, and I haven't really tested much beyond making rooms and playing (I'm sure there are a lot of commands I haven't triggered that are going to crash it, esp. on x64), but it does run.

**Comment by chopraaa** [comment]
Baby steps, man. This is great news!

**Comment by sagiweizmann** [comment]
hey guys :) , someone can help me with the compiling process?

**Comment by manokara** [comment]
Great stuff! Running GunZ on WINE is troublesome, the launcher works but the client crashes :/ Out of curiosity, how much work would it be to replace the DirectX code for something like [bgfx](https://github.com/bkaradzic/bgfx)? I think once that's done it would allow making a cross-platform client easier.

**Comment by chopraaa** [comment]
Just for the record, my suggestion was only for running the building and running the _server_ on Linux, not the client itself.

**Comment by manokara** [comment]
You're right. I should open a separate issue for that.

**Comment by sagiweizmann** [comment]
Can run the server on WINE On linux , just install mssql on ubuntu , link it to ODBCAD32 on WINE ,
and Then change the ticketUse in matchserver solution in vs2015 , to default 0 , VOILA.

**Comment by chopraaa** [comment]
@sagiweizmann Please don't make such suggestions.

Wine is as cancerous as it gets on a nix environment and should be avoided.

**Comment by Asunaya** [comment]
Heyo, I got the MSSQL stuff to stop using MFC in 2727cde, so MSSQL works on Linux now too, via unixODBC. I think I'm going to close this issue now since the server seems to be ported. I'm sure there are still related bugs though, so feel free to open another if you find one.

If anyone wants to try it out, I've used [this script](https://pastebin.com/raw/EXW7CzzA) while testing to set up the server with MSSQL on Ubuntu servers, in case it helps.
