### ISSUE TITLE
Elimination notices don't disappear when pressing T in replays

### ISSUE THREAD

**Issue by phugen** [Asunaya/RefinedGunz#20]
Just like the title states. In previous versions of the game, pressing T would remove the black bars as well as hide the entire chat along with elimination notices, not just the chat itself (likely because the eliminations were directly part of the chat or something). I think RGunz should mimick this behavior because having a clean screen is nice, especially for recording replays.

**Comment by Asunaya** [comment]
Turns out it's actually supposed to be H, [they just forgot a break statement](https://github.com/Asunaya/RefinedGunz/blob/5e3a5ae5dcd10986d51661f0e40ec236205480ef/Gunz/ZGameInput.cpp#L402-L403). That's pretty funny, actually.

Anyway, it's actually just failing to hide the chat, which is caused by the fact that the chat is essentially a completely new thing created from scratch, and I've forgotten to plug it into various places.

You can also apply a hacky fix by just moving the chat frame out of bounds.
