### ISSUE TITLE
few things

### ISSUE THREAD

**Issue by Cmdxz** [Asunaya/RefinedGunz#23]
Interface  http://prntscr.com/gtv564 /interfacefix 0/1/2 did not work

No portal at quest https://prnt.sc/gtv59u

And the flip animation happens, but it does not flip characters or quest objects.

**Comment by Cmdxz** [comment]
Any way to fix these? I've tried it with different mrs files, but I haven't had much luck. Changing out the model files from your client to the Phoenix 2008 client files fixed my quests so I can atleast shoot an NPC without it crashing.

**Comment by Cmdxz** [comment]
After a good amount of searching, I am assuming the massive problem is with one of these files.

in zip : model/man/man_sword_guard_start2.elu.ani file not found!! 
 in zip : model/woman/woman_sword_guard_start2.elu.ani file not found!! 
 in zip : model/woman/woman_sword_guard_block_1.elu.ani file not found!!

**Comment by Cmdxz** [comment]
After further inspection, it looks like I'm not able to load the little shooting goblins which is also crashing the game. I will try to find these files and send them to you if I get it fixed and not crashing.

**Comment by Asunaya** [comment]
The interface truncation is a bug that was fixed a while ago I think (52ab504?), and flips not happening are probably due to the "no flips" stage option being on (should probably be off by default instead).

I'm not sure what the "massive problem" is, but those 3 ".ani file not found" mlog messages are normal; they occur in all clients as far as I recall. Should probably still fix or silence them, since people seem to misidentify them as a problem pretty often.

I'm not sure what's wrong with quests. I can try looking into that later, and also publishing a more up-to-date release.

I don't really play quests so that always seems to be in a state of disrepair due to my inattention; sorry about that.

**Comment by Cmdxz** [comment]
It seemed to have fixed itself out when I rebuilt the Gunz.exe and changed my config.xml file(?)

Thank you for the super quick response! I suspect the option should be in the misc settings, however I don't see them there. I've commented the NoFLIP open as a whole and I'm going to try.

**Comment by Asunaya** [comment]
Again: The no flips thing is a **stage** option, as in reachable from the game room settings. *Not* a config.xml option.

Going to bed; will look at quest stuff sometime tomorrow, perhaps.

**Comment by Cmdxz** [comment]
I am an idiot, thank you! 
Also after firing a bunch of the MG http://prntscr.com/gtw3kl the trails are stuck there. I am unsure how to fix this.

**Comment by Asunaya** [comment]
Yeah, that's a known bug. Not sure what causes it, will look into that as well.

**Comment by Asunaya** [comment]
Fixed the tracer thing in 58f9392.

**Comment by Asunaya** [comment]
I posted a new release, [v0.5.0](https://github.com/Asunaya/RefinedGunz/releases/tag/v0.5.0), which I think has all of these issues resolved. Let me know if you run into any other problems. Thanks.
