### ISSUE TITLE
After adding gun game SHOP and INVENTORY do not work

### ISSUE THREAD

**Issue by Cmdxz** [Asunaya/RefinedGunz#24]
Any idea why this is? No XMLs were changed, and nothing should've effected them. but I am unable to open shop or inventory after this game mode has been put in.

**Comment by Asunaya** [comment]
Hey, I think this is because 6c1b03f changed the widgets the game uses and the latest Github release doesn't have the new Lobby and Stage XMLs.

[Here](https://pastebin.com/raw/p1TA0TGn) is the correct Lobby.xml, and [here](https://pastebin.com/raw/YtMb18QB) is the correct Stage.xml.

Let me know if that resolves the issue.

**Comment by Cmdxz** [comment]
That was the fix! Thank you very much!
